name: 🚀 Deploy to InfinityFree
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploying Files
    runs-on: ubuntu-latest
    # السطر التالي يحل مشكلة التنبيه ويجبر النظام على استخدام Node 24
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./arebcmpetars-shech-stecke.com/htdocs/
